name: astegod
description: Ãstegod.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.0
  flutter_localization: ^0.1.12
  ionicons: ^0.2.2
  flutter_svg: ^2.0.7
  google_sign_in: ^6.1.4
  flutter_native_splash: ^2.3.2
  http: ^1.1.0
  flutter_compass: ^0.8.0
  video_player: any
  loading_animation_widget: ^1.2.0+4
  masonry_grid: ^1.0.0

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  chewie: ^1.7.1

flutter_native_splash:

  android_12:
   color: "#f8f8f8"
   color_dark: "#1e1e1e"

   image: assets/imagenes/icono-base-oscuro.png
   image_dark: assets/imagenes/icono-base.png


  android: true
  ios: true
  web: false

  color_android: "#F8F8F8"
  color_dark_android: "#1E1E1E"
  color_ios: "#F8F8F8"
  color_dark_ios: "#1E1E1E"

  image_android: assets/imagenes/icono-base-oscuro.png
  image_dark_android: assets/imagenes/icono-base.png
  image_ios: assets/imagenes/icono-base-oscuro.png
  image_dark_ios: assets/imagenes/icono-base.png
  image: assets/imagenes/icono-base.png

flutter:

  uses-material-design: true

  assets:
   - assets/imagenes/logo-texto-claro.svg
   - assets/imagenes/logo-texto-oscuro.svg
   - assets/imagenes/isotipo-oscuro.svg
   - assets/imagenes/isotipo-claro.svg

  fonts:
    - family: LeaugeSpartan
      fonts:
        - asset: assets/fonts/LeagueSpartan-Bold.ttf
    - family: LeaugeSpartanLite
      fonts:
        - asset: assets/fonts/LeagueSpartan-Regular.ttf
    - family: Normal
      fonts:
        - asset: assets/fonts/Gabarito-VariableFont_wght.ttf
    - family: LexendExa
      fonts:
        - asset: assets/fonts/LexendExa-VariableFont_wght.ttf
    - family: pon
      fonts:
        - asset: assets/fonts/Lora-VariableFont_wght.ttf
    - family: may
      fonts:
        - asset: assets/fonts/PTMono-Regular.ttf
    - family: bay
      fonts:
        - asset: assets/fonts/Rubik-VariableFont_wght.ttf
    - family: are
      fonts:
        - asset: assets/fonts/PixelifySans-VariableFont_wght.ttf
    - family: cag
      fonts:
        - asset: assets/fonts/MeowScript-Regular.ttf


flutter_intl:
  enabled: true
